version: "3.1"
services:
  #### SETUP POSTGRES container #####
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "MyPostgresPassword"
      POSTGRES_USER: "MyPostgresUser"
      POSTGRES_DB: "postgres"
    expose:
      - 5432
    ports:
      - "5432:5432"
